-- ALTER SESSION SET container = ORCLPDB1;
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

--
-- Users
--
CREATE USER User_ IDENTIFIED BY 1234 DEFAULT TABLESPACE USERS;
GRANT CREATE CLUSTER TO "User_";
GRANT CREATE DATABASE LINK TO "User_" ;
GRANT CREATE SESSION TO "User_" ;
GRANT CREATE TRIGGER TO "User_" ;
GRANT CREATE ANY TRIGGER TO "User_" ;
GRANT UNLIMITED TABLESPACE TO "User_" ;
GRANT CREATE ANY LIBRARY TO "User_" ;
GRANT CREATE SYNONYM TO "User_" ;
GRANT CREATE SEQUENCE TO "User_" ;
GRANT CREATE SNAPSHOT TO "User_" ;
GRANT CREATE TABLE TO "User_" ;
GRANT CREATE VIEW TO "User_" ;
GRANT SELECT ANY TABLE TO "User_" ;
GRANT CREATE TYPE TO "User_" ;
GRANT CREATE LIBRARY TO "User_" ;
GRANT CREATE DIMENSION TO "User_" ;
GRANT CREATE OPERATOR TO "User_" ;
GRANT CREATE INDEXTYPE TO "User_" ;
GRANT IMP_FULL_DATABASE TO "User_" ;
GRANT IMPORT FULL DATABASE TO "User_" ;

--
-- Directory
--
CREATE OR REPLACE DIRECTORY IMP_DIR AS '/opt/oracle/import';
GRANT WRITE,READ ON DIRECTORY IMP_DIR TO "User_" ;